id: THENAWABX_GIT_CONFIG_HUNTER
info:
  name: 📂 Nawab-Git-Config-Hunter 📂
  author: thenawabx
  severity: high

http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "repositoryformatversion"
          - "[remote \"origin\"]"
          - "url ="
        condition: and

      - type: word
        part: body
        negative: true
        words:
          - "<html"
          - "<body"
          - "404"
          - "Example Repository"

    extractors:
      - type: regex
        part: body
        regex:
          - "url = (.*)"
